#!/usr/bin/env python3
"""
Regenerates scripts-data.js from scripts_data.py.

Usage:
    1. Edit scripts_data.py — add a new dict to the SCRIPTS list, or edit an
       existing one. Copy an existing entry as your template; the required
       shape is:
           {
             "slug": "unique-url-safe-id",
             "title": "Display Title",
             "summary": "One-line description.",
             "category": "hardware" | "backend" | "web" | "tooling",
             "tags": ["short", "pill", "labels"],
             "langs": [
                 {"id": "python", "label": "Python", "code": "..."},
                 {"id": "js", "label": "Node", "code": "..."},
             ],
         }
    2. Run: python3 generate.py
    3. Commit the updated scripts-data.js alongside scripts_data.py.

No HTML editing required — scripts.html renders every card from this data
at load time, so the script count can grow without the page's source
getting longer or riskier to hand-edit.
"""
import json
from scripts_data import SCRIPTS

OUTPUT = "scripts-data.js"

with open(OUTPUT, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by generate.py from scripts_data.py — do not hand-edit.\n")
    f.write("// To add or change a script: edit scripts_data.py, then run: python3 generate.py\n")
    f.write("const SCRIPTS_DATA = ")
    f.write(json.dumps(SCRIPTS, ensure_ascii=False, indent=2))
    f.write(";\n")

print(f"Wrote {len(SCRIPTS)} scripts to {OUTPUT}")
