// Auto-generated by generate.py from scripts_data.py — do not hand-edit.
// To add or change a script: edit scripts_data.py, then run: python3 generate.py
const SCRIPTS_DATA = [
  {
    "slug": "servo-sweep",
    "title": "Servo Sweep & Position Control",
    "summary": "Get a servo moving predictably before you touch your real project.",
    "category": "hardware",
    "tags": [
      "motor & servo",
      "embedded"
    ],
    "langs": [
      {
        "id": "cpp",
        "label": "Arduino C++",
        "code": "#include <Servo.h>\n\n// ── CONFIG ─────────────────────\nconst int SERVO_PIN   = 9;     // TODO: your PWM-capable pin\nconst int MIN_ANGLE   = 0;\nconst int MAX_ANGLE   = 180;\nconst int STEP_DELAY  = 15;    // ms between steps\n\nServo myServo;\nint angle = MIN_ANGLE;\nint direction = 1;\n\nvoid setup() {\n  myServo.attach(SERVO_PIN);\n  myServo.write(angle);\n}\n\nvoid loop() {\n  myServo.write(angle);\n  angle += direction;\n\n  if (angle >= MAX_ANGLE || angle <= MIN_ANGLE) {\n    direction *= -1;\n  }\n  delay(STEP_DELAY);\n\n  // TODO: replace the sweep with your real logic\n}\n\nvoid moveTo(int targetAngle) {\n  targetAngle = constrain(targetAngle, MIN_ANGLE, MAX_ANGLE);\n  myServo.write(targetAngle);\n}"
      },
      {
        "id": "python",
        "label": "CircuitPython",
        "code": "import time\nimport board\nimport pwmio\nfrom adafruit_motor import servo\n\n# ── CONFIG ─────────────────────\nSERVO_PIN = board.D9      # TODO: your PWM-capable pin\nMIN_ANGLE = 0\nMAX_ANGLE = 180\nSTEP_DELAY = 0.015\n\npwm = pwmio.PWMOut(SERVO_PIN, duty_cycle=2 ** 15, frequency=50)\nmy_servo = servo.Servo(pwm)\n\nangle = MIN_ANGLE\ndirection = 1\n\ndef move_to(target_angle):\n    target_angle = max(MIN_ANGLE, min(MAX_ANGLE, target_angle))\n    my_servo.angle = target_angle\n\nwhile True:\n    my_servo.angle = angle\n    angle += direction\n\n    if angle >= MAX_ANGLE or angle <= MIN_ANGLE:\n        direction *= -1\n\n    time.sleep(STEP_DELAY)\n\n    # TODO: replace the sweep with your real logic"
      }
    ]
  },
  {
    "slug": "dc-motor-driver",
    "title": "DC Motor — PWM Driver",
    "summary": "Direction and speed control through a standard H-bridge (L298N / TB6612-style).",
    "category": "hardware",
    "tags": [
      "motor & servo",
      "embedded"
    ],
    "langs": [
      {
        "id": "cpp",
        "label": "Arduino C++",
        "code": "// ── CONFIG ─────────────────────\nconst int PIN_IN1 = 5;   // TODO: H-bridge input 1\nconst int PIN_IN2 = 6;   // TODO: H-bridge input 2\nconst int PIN_PWM = 9;   // TODO: enable / speed pin\n\nvoid setup() {\n  pinMode(PIN_IN1, OUTPUT);\n  pinMode(PIN_IN2, OUTPUT);\n  pinMode(PIN_PWM, OUTPUT);\n  stopMotor();\n}\n\nvoid loop() {\n  // TODO: replace this demo pattern with real control logic\n  forward(180);   delay(1500);\n  stopMotor();    delay(400);\n  backward(180);  delay(1500);\n  stopMotor();    delay(400);\n}\n\nvoid forward(int speed) {\n  digitalWrite(PIN_IN1, HIGH);\n  digitalWrite(PIN_IN2, LOW);\n  analogWrite(PIN_PWM, constrain(speed, 0, 255));\n}\n\nvoid backward(int speed) {\n  digitalWrite(PIN_IN1, LOW);\n  digitalWrite(PIN_IN2, HIGH);\n  analogWrite(PIN_PWM, constrain(speed, 0, 255));\n}\n\nvoid stopMotor() {\n  digitalWrite(PIN_IN1, LOW);\n  digitalWrite(PIN_IN2, LOW);\n  analogWrite(PIN_PWM, 0);\n}"
      },
      {
        "id": "python",
        "label": "Raspberry Pi (Python)",
        "code": "import RPi.GPIO as GPIO\nimport time\n\n# ── CONFIG ─────────────────────\nPIN_IN1 = 17\nPIN_IN2 = 27\nPIN_PWM = 18\n\nGPIO.setmode(GPIO.BCM)\nGPIO.setup(PIN_IN1, GPIO.OUT)\nGPIO.setup(PIN_IN2, GPIO.OUT)\nGPIO.setup(PIN_PWM, GPIO.OUT)\npwm = GPIO.PWM(PIN_PWM, 1000)\npwm.start(0)\n\ndef forward(speed):\n    GPIO.output(PIN_IN1, GPIO.HIGH)\n    GPIO.output(PIN_IN2, GPIO.LOW)\n    pwm.ChangeDutyCycle(max(0, min(100, speed)))\n\ndef backward(speed):\n    GPIO.output(PIN_IN1, GPIO.LOW)\n    GPIO.output(PIN_IN2, GPIO.HIGH)\n    pwm.ChangeDutyCycle(max(0, min(100, speed)))\n\ndef stop_motor():\n    GPIO.output(PIN_IN1, GPIO.LOW)\n    GPIO.output(PIN_IN2, GPIO.LOW)\n    pwm.ChangeDutyCycle(0)\n\ntry:\n    # TODO: replace this demo pattern with real control logic\n    while True:\n        forward(70);  time.sleep(1.5)\n        stop_motor(); time.sleep(0.4)\n        backward(70); time.sleep(1.5)\n        stop_motor(); time.sleep(0.4)\nexcept KeyboardInterrupt:\n    pwm.stop()\n    GPIO.cleanup()"
      }
    ]
  },
  {
    "slug": "addressable-led",
    "title": "Addressable LED Pattern",
    "summary": "A rotating rainbow across a NeoPixel/WS2812 strip — swap the pattern math for your own.",
    "category": "hardware",
    "tags": [
      "lighting",
      "embedded"
    ],
    "langs": [
      {
        "id": "cpp",
        "label": "Arduino C++ (FastLED)",
        "code": "#include <FastLED.h>\n\n// ── CONFIG ─────────────────────\n#define LED_PIN     6      // TODO: your data pin\n#define NUM_LEDS    30\n#define BRIGHTNESS  80\n\nCRGB leds[NUM_LEDS];\n\nvoid setup() {\n  FastLED.addLeds<WS2812B, LED_PIN, GRB>(leds, NUM_LEDS);\n  FastLED.setBrightness(BRIGHTNESS);\n}\n\nvoid loop() {\n  // TODO: replace with your real pattern\n  static uint8_t hue = 0;\n  for (int i = 0; i < NUM_LEDS; i++) {\n    leds[i] = CHSV(hue + (i * 256 / NUM_LEDS), 255, 255);\n  }\n  FastLED.show();\n  hue++;\n  delay(20);\n}"
      },
      {
        "id": "python",
        "label": "CircuitPython",
        "code": "import board\nimport neopixel\nimport time\n\n# ── CONFIG ─────────────────────\nLED_PIN = board.D6\nNUM_LEDS = 30\nBRIGHTNESS = 0.3\n\npixels = neopixel.NeoPixel(LED_PIN, NUM_LEDS, brightness=BRIGHTNESS, auto_write=False)\n\ndef wheel(pos):\n    if pos < 85:\n        return (255 - pos * 3, pos * 3, 0)\n    elif pos < 170:\n        pos -= 85\n        return (0, 255 - pos * 3, pos * 3)\n    else:\n        pos -= 170\n        return (pos * 3, 0, 255 - pos * 3)\n\nhue = 0\nwhile True:\n    # TODO: replace with your real pattern\n    for i in range(NUM_LEDS):\n        pixel_index = (i * 256 // NUM_LEDS) + hue\n        pixels[i] = wheel(pixel_index & 255)\n    pixels.show()\n    hue = (hue + 1) % 256\n    time.sleep(0.02)"
      }
    ]
  },
  {
    "slug": "temp-humidity-sensor",
    "title": "Temperature & Humidity Sensor Reader",
    "summary": "Poll a DHT22 on an interval and hand off clean readings, with bad-read retries baked in.",
    "category": "hardware",
    "tags": [
      "sensors",
      "embedded"
    ],
    "langs": [
      {
        "id": "cpp",
        "label": "Arduino C++",
        "code": "#include <DHT.h>\n\n// ── CONFIG ─────────────────────\n#define DHT_PIN     2        // TODO: your data pin\n#define DHT_TYPE    DHT22\nconst unsigned long READ_INTERVAL = 2000;  // ms, DHT22 min ~2s\n\nDHT dht(DHT_PIN, DHT_TYPE);\nunsigned long lastRead = 0;\n\nvoid setup() {\n  Serial.begin(9600);\n  dht.begin();\n}\n\nvoid loop() {\n  if (millis() - lastRead >= READ_INTERVAL) {\n    lastRead = millis();\n    readSensor();\n  }\n  // TODO: replace the Serial print with your real logic\n}\n\nvoid readSensor() {\n  float humidity = dht.readHumidity();\n  float tempC = dht.readTemperature();\n\n  if (isnan(humidity) || isnan(tempC)) {\n    Serial.println(\"Read failed, will retry next interval\");\n    return;\n  }\n\n  Serial.print(\"Temp: \"); Serial.print(tempC);\n  Serial.print(\"C  Humidity: \"); Serial.print(humidity); Serial.println(\"%\");\n}"
      },
      {
        "id": "python",
        "label": "CircuitPython",
        "code": "import time\nimport board\nimport adafruit_dht\n\n# ── CONFIG ─────────────────────\nDHT_PIN = board.D2       # TODO: your data pin\nREAD_INTERVAL = 2.0      # seconds, DHT22 min ~2s\n\ndht = adafruit_dht.DHT22(DHT_PIN)\n\ndef read_sensor():\n    try:\n        temp_c = dht.temperature\n        humidity = dht.humidity\n        print(f\"Temp: {temp_c}C  Humidity: {humidity}%\")\n        return temp_c, humidity\n    except RuntimeError as e:\n        # DHT sensors drop reads often — this is normal, just retry\n        print(f\"Read failed ({e.args[0]}), will retry next interval\")\n        return None, None\n\nwhile True:\n    read_sensor()   # TODO: replace with your real logic\n    time.sleep(READ_INTERVAL)"
      }
    ]
  },
  {
    "slug": "button-debounce",
    "title": "Button Input & Debounce",
    "summary": "Clean single-press detection from a noisy mechanical switch — no phantom double-fires.",
    "category": "hardware",
    "tags": [
      "input",
      "embedded"
    ],
    "langs": [
      {
        "id": "cpp",
        "label": "Arduino C++",
        "code": "// ── CONFIG ─────────────────────\nconst int BUTTON_PIN = 2;         // TODO: your input pin\nconst unsigned long DEBOUNCE_MS = 40;\n\nint lastReading = HIGH;\nint stableState = HIGH;\nunsigned long lastChangeTime = 0;\n\nvoid setup() {\n  Serial.begin(9600);\n  pinMode(BUTTON_PIN, INPUT_PULLUP);   // wired to GND when pressed\n}\n\nvoid loop() {\n  int reading = digitalRead(BUTTON_PIN);\n\n  if (reading != lastReading) {\n    lastChangeTime = millis();\n  }\n\n  if (millis() - lastChangeTime > DEBOUNCE_MS) {\n    if (reading != stableState) {\n      stableState = reading;\n      if (stableState == LOW) {\n        onPress();   // TODO: replace with your real logic\n      }\n    }\n  }\n\n  lastReading = reading;\n}\n\nvoid onPress() {\n  Serial.println(\"Button pressed\");\n}"
      },
      {
        "id": "python",
        "label": "Raspberry Pi (Python)",
        "code": "import RPi.GPIO as GPIO\nimport time\n\n# ── CONFIG ─────────────────────\nBUTTON_PIN = 17     # TODO: your input pin\nDEBOUNCE_MS = 200\n\ndef on_press(channel):\n    # TODO: replace with your real logic\n    print(\"Button pressed\")\n\nGPIO.setmode(GPIO.BCM)\nGPIO.setup(BUTTON_PIN, GPIO.IN, pull_up_down=GPIO.PUD_UP)\nGPIO.add_event_detect(BUTTON_PIN, GPIO.FALLING,\n                       callback=on_press, bouncetime=DEBOUNCE_MS)\n\ntry:\n    while True:\n        time.sleep(1)\nexcept KeyboardInterrupt:\n    GPIO.cleanup()"
      }
    ]
  },
  {
    "slug": "web-app-starter",
    "title": "Web App Starter, No Build Step",
    "summary": "State, render, and event handling in one file — open it and go.",
    "category": "web",
    "tags": [
      "web app",
      "no build"
    ],
    "langs": [
      {
        "id": "js",
        "label": "Vanilla JS",
        "code": "<!-- index.html — open directly in a browser, no server needed -->\n<div id=\"app\"></div>\n<script>\n// ── STATE ─────────────────────\nconst state = { items: [] };   // TODO: shape this to your data\n\n// ── RENDER ────────────────────\nfunction render() {\n  const app = document.getElementById('app');\n  app.innerHTML = `\n    <h1>My App</h1>\n    <button data-action=\"add\">Add item</button>\n    <ul>\n      ${state.items.map((item, i) =>\n        `<li>${item} <button data-action=\"remove\" data-index=\"${i}\">x</button></li>`\n      ).join('')}\n    </ul>\n  `;\n}\n\n// ── EVENTS (delegated — survives re-renders) ─\ndocument.getElementById('app').addEventListener('click', (e) => {\n  const action = e.target.dataset.action;\n  if (action === 'add') {\n    state.items.push(`Item ${state.items.length + 1}`);\n    render();\n  }\n  if (action === 'remove') {\n    state.items.splice(Number(e.target.dataset.index), 1);\n    render();\n  }\n});\n\nrender();\n</script>"
      },
      {
        "id": "python",
        "label": "Python (Flask)",
        "code": "from flask import Flask, render_template_string, request, jsonify\n\napp = Flask(__name__)\n\n# ── STATE ─────────────────────\nstate = {\"items\": []}   # TODO: shape this to your data\n\nPAGE = \"\"\"\n<h1>My App</h1>\n<button onclick=\"addItem()\">Add item</button>\n<ul id=\"list\"></ul>\n<script>\nasync function refresh() {\n  const res = await fetch('/items');\n  const data = await res.json();\n  document.getElementById('list').innerHTML =\n    data.items.map((item, i) => `<li>${item} <button onclick=\"removeItem(${i})\">x</button></li>`).join('');\n}\nasync function addItem() { await fetch('/items', { method: 'POST' }); refresh(); }\nasync function removeItem(i) { await fetch(`/items/${i}`, { method: 'DELETE' }); refresh(); }\nrefresh();\n</script>\n\"\"\"\n\n@app.route(\"/\")\ndef index():\n    return render_template_string(PAGE)\n\n@app.route(\"/items\", methods=[\"GET\", \"POST\"])\ndef items():\n    if request.method == \"POST\":\n        state[\"items\"].append(f\"Item {len(state['items']) + 1}\")\n    return jsonify(state)\n\n@app.route(\"/items/<int:i>\", methods=[\"DELETE\"])\ndef remove_item(i):\n    if 0 <= i < len(state[\"items\"]):\n        state[\"items\"].pop(i)\n    return jsonify(state)\n\nif __name__ == \"__main__\":\n    app.run(debug=True)"
      }
    ]
  },
  {
    "slug": "live-search",
    "title": "Debounced Live Search / Filter",
    "summary": "Filters a list as the user types without hammering re-renders on every keystroke.",
    "category": "web",
    "tags": [
      "web app",
      "no build"
    ],
    "langs": [
      {
        "id": "js",
        "label": "Vanilla JS",
        "code": "<!-- index.html — open directly in a browser, no server needed -->\n<input id=\"search\" placeholder=\"Search...\" />\n<ul id=\"results\"></ul>\n<script>\n// ── DATA ─────────────────────\nconst items = [\"Apple\", \"Banana\", \"Cherry\"];   // TODO: your real data\n\n// ── DEBOUNCE HELPER ───────────\nfunction debounce(fn, delay) {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), delay);\n  };\n}\n\nfunction render(list) {\n  document.getElementById('results').innerHTML =\n    list.map(item => `<li>${item}</li>`).join('');\n}\n\nconst onSearch = debounce((query) => {\n  const filtered = items.filter(i =>\n    i.toLowerCase().includes(query.toLowerCase())\n  );\n  render(filtered);   // TODO: replace with your real filtering logic\n}, 200);\n\ndocument.getElementById('search').addEventListener('input', (e) => {\n  onSearch(e.target.value);\n});\n\nrender(items);\n</script>"
      },
      {
        "id": "python",
        "label": "Python (Flask)",
        "code": "from flask import Flask, render_template_string, request, jsonify\n\napp = Flask(__name__)\n\n# ── DATA ─────────────────────\nITEMS = [\"Apple\", \"Banana\", \"Cherry\"]   # TODO: your real data\n\nPAGE = \"\"\"\n<input id=\"search\" placeholder=\"Search...\" />\n<ul id=\"results\"></ul>\n<script>\nlet timer;\ndocument.getElementById('search').addEventListener('input', (e) => {\n  clearTimeout(timer);\n  timer = setTimeout(() => search(e.target.value), 200);\n});\nasync function search(query) {\n  const res = await fetch(`/search?q=${encodeURIComponent(query)}`);\n  const data = await res.json();\n  document.getElementById('results').innerHTML =\n    data.items.map(i => `<li>${i}</li>`).join('');\n}\nsearch('');\n</script>\n\"\"\"\n\n@app.route(\"/\")\ndef index():\n    return render_template_string(PAGE)\n\n@app.route(\"/search\")\ndef search():\n    query = request.args.get(\"q\", \"\").lower()\n    matches = [i for i in ITEMS if query in i.lower()]   # TODO: replace with your real logic\n    return jsonify({\"items\": matches})\n\nif __name__ == \"__main__\":\n    app.run(debug=True)"
      }
    ]
  },
  {
    "slug": "api-data-fetcher",
    "title": "API Data Fetcher — Loading & Error States",
    "summary": "The three-state fetch pattern every UI needs: loading, error, and success, handled once.",
    "category": "web",
    "tags": [
      "web app",
      "API"
    ],
    "langs": [
      {
        "id": "js",
        "label": "Vanilla JS",
        "code": "<!-- index.html — open directly in a browser, no server needed -->\n<div id=\"app\"></div>\n<script>\n// ── CONFIG ─────────────────────\nconst API_URL = \"https://api.example.com/data\";   // TODO: your endpoint\n\nconst state = { status: \"loading\", data: null, error: null };\n\nfunction render() {\n  const app = document.getElementById('app');\n  if (state.status === \"loading\") {\n    app.innerHTML = \"<p>Loading...</p>\";\n  } else if (state.status === \"error\") {\n    app.innerHTML = `<p>Something went wrong: ${state.error}</p>`;\n  } else {\n    // TODO: replace with your real rendering\n    app.innerHTML = `<pre>${JSON.stringify(state.data, null, 2)}</pre>`;\n  }\n}\n\nasync function load() {\n  state.status = \"loading\";\n  render();\n  try {\n    const res = await fetch(API_URL);\n    if (!res.ok) throw new Error(`HTTP ${res.status}`);\n    state.data = await res.json();\n    state.status = \"success\";\n  } catch (err) {\n    state.error = err.message;\n    state.status = \"error\";\n  }\n  render();\n}\n\nload();\n</script>"
      },
      {
        "id": "python",
        "label": "Python (requests)",
        "code": "import requests\nimport time\n\n# ── CONFIG ─────────────────────\nAPI_URL = \"https://api.example.com/data\"   # TODO: your endpoint\nMAX_RETRIES = 3\nRETRY_DELAY = 1.5   # seconds\n\ndef load(url):\n    last_error = None\n    for attempt in range(1, MAX_RETRIES + 1):\n        try:\n            resp = requests.get(url, timeout=5)\n            resp.raise_for_status()\n            return resp.json()\n        except requests.RequestException as e:\n            last_error = e\n            print(f\"Attempt {attempt} failed: {e}\")\n            time.sleep(RETRY_DELAY)\n    raise RuntimeError(f\"Giving up after {MAX_RETRIES} attempts: {last_error}\")\n\nif __name__ == \"__main__\":\n    try:\n        data = load(API_URL)\n        print(data)   # TODO: replace with your real handling\n    except RuntimeError as e:\n        print(f\"Error: {e}\")"
      }
    ]
  },
  {
    "slug": "rest-api-starter",
    "title": "REST API Starter",
    "summary": "Basic CRUD endpoints wired up and ready to point at a real data store.",
    "category": "backend",
    "tags": [
      "backend",
      "API"
    ],
    "langs": [
      {
        "id": "python",
        "label": "Python (FastAPI)",
        "code": "from fastapi import FastAPI, HTTPException\nfrom pydantic import BaseModel\n\napp = FastAPI()\n\n# ── MODEL ─────────────────────\nclass Item(BaseModel):\n    name: str          # TODO: shape this to your data\n\ndb: list[Item] = []\n\n@app.get(\"/items\")\ndef list_items():\n    return db\n\n@app.post(\"/items\")\ndef create_item(item: Item):\n    db.append(item)\n    return item\n\n@app.get(\"/items/{item_id}\")\ndef get_item(item_id: int):\n    if item_id >= len(db):\n        raise HTTPException(status_code=404, detail=\"Not found\")\n    return db[item_id]\n\n@app.delete(\"/items/{item_id}\")\ndef delete_item(item_id: int):\n    if item_id >= len(db):\n        raise HTTPException(status_code=404, detail=\"Not found\")\n    return db.pop(item_id)\n\n# Run with: uvicorn main:app --reload"
      },
      {
        "id": "js",
        "label": "Node (Express)",
        "code": "const express = require('express');\nconst app = express();\napp.use(express.json());\n\n// ── STATE ─────────────────────\nlet items = [];   // TODO: shape this to your data\n\napp.get('/items', (req, res) => {\n  res.json(items);\n});\n\napp.post('/items', (req, res) => {\n  const item = req.body;   // TODO: validate\n  items.push(item);\n  res.status(201).json(item);\n});\n\napp.get('/items/:id', (req, res) => {\n  const item = items[req.params.id];\n  if (!item) return res.status(404).json({ error: 'Not found' });\n  res.json(item);\n});\n\napp.delete('/items/:id', (req, res) => {\n  if (!items[req.params.id]) return res.status(404).json({ error: 'Not found' });\n  const [removed] = items.splice(req.params.id, 1);\n  res.json(removed);\n});\n\napp.listen(3000, () => console.log('Listening on :3000'));"
      }
    ]
  },
  {
    "slug": "websocket-server",
    "title": "Realtime WebSocket Server",
    "summary": "Broadcasts every message to all connected clients — the base for chat, multiplayer, or live dashboards.",
    "category": "backend",
    "tags": [
      "backend",
      "realtime"
    ],
    "langs": [
      {
        "id": "python",
        "label": "Python (websockets)",
        "code": "import asyncio\nimport websockets\n\n# ── STATE ─────────────────────\nclients = set()\n\nasync def handler(websocket):\n    clients.add(websocket)\n    try:\n        async for message in websocket:\n            # TODO: replace with your real message handling\n            for client in clients:\n                if client != websocket:\n                    await client.send(message)\n    finally:\n        clients.remove(websocket)\n\nasync def main():\n    async with websockets.serve(handler, \"0.0.0.0\", 8765):\n        await asyncio.Future()\n\nif __name__ == \"__main__\":\n    asyncio.run(main())"
      },
      {
        "id": "js",
        "label": "Node (ws)",
        "code": "const { WebSocketServer } = require('ws');\nconst wss = new WebSocketServer({ port: 8765 });\n\n// ── STATE ─────────────────────\nconst clients = new Set();\n\nwss.on('connection', (ws) => {\n  clients.add(ws);\n\n  ws.on('message', (data) => {\n    // TODO: replace with your real message handling\n    for (const client of clients) {\n      if (client !== ws) client.send(data.toString());\n    }\n  });\n\n  ws.on('close', () => clients.delete(ws));\n});\n\nconsole.log('WebSocket server on :8765');"
      }
    ]
  },
  {
    "slug": "sqlite-persistence",
    "title": "SQLite Persistence Layer",
    "summary": "A tiny data layer with a real table and connection handling, so you stop losing state on restart.",
    "category": "backend",
    "tags": [
      "backend",
      "database"
    ],
    "langs": [
      {
        "id": "python",
        "label": "Python (sqlite3)",
        "code": "import sqlite3\n\n# ── CONFIG ─────────────────────\nDB_PATH = \"app.db\"   # TODO: your database file\n\ndef get_connection():\n    conn = sqlite3.connect(DB_PATH)\n    conn.row_factory = sqlite3.Row\n    return conn\n\ndef init_db():\n    with get_connection() as conn:\n        conn.execute(\"\"\"\n            CREATE TABLE IF NOT EXISTS items (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                name TEXT NOT NULL\n            )\n        \"\"\")   # TODO: shape this to your data\n\ndef add_item(name):\n    with get_connection() as conn:\n        cur = conn.execute(\"INSERT INTO items (name) VALUES (?)\", (name,))\n        return cur.lastrowid\n\ndef list_items():\n    with get_connection() as conn:\n        rows = conn.execute(\"SELECT * FROM items\").fetchall()\n        return [dict(row) for row in rows]\n\ndef delete_item(item_id):\n    with get_connection() as conn:\n        conn.execute(\"DELETE FROM items WHERE id = ?\", (item_id,))\n\nif __name__ == \"__main__\":\n    init_db()\n    add_item(\"Example\")   # TODO: replace with your real logic\n    print(list_items())"
      },
      {
        "id": "js",
        "label": "Node (better-sqlite3)",
        "code": "const Database = require('better-sqlite3');\n\n// ── CONFIG ─────────────────────\nconst DB_PATH = 'app.db';   // TODO: your database file\n\nconst db = new Database(DB_PATH);\n\nfunction initDb() {\n  db.exec(`\n    CREATE TABLE IF NOT EXISTS items (\n      id INTEGER PRIMARY KEY AUTOINCREMENT,\n      name TEXT NOT NULL\n    )\n  `);   // TODO: shape this to your data\n}\n\nfunction addItem(name) {\n  const stmt = db.prepare('INSERT INTO items (name) VALUES (?)');\n  const info = stmt.run(name);\n  return info.lastInsertRowid;\n}\n\nfunction listItems() {\n  return db.prepare('SELECT * FROM items').all();\n}\n\nfunction deleteItem(id) {\n  db.prepare('DELETE FROM items WHERE id = ?').run(id);\n}\n\ninitDb();\naddItem('Example');   // TODO: replace with your real logic\nconsole.log(listItems());"
      }
    ]
  },
  {
    "slug": "file-watcher",
    "title": "File Watcher & Automation",
    "summary": "Watches a folder and fires your own logic on any create, edit, or delete.",
    "category": "tooling",
    "tags": [
      "automation",
      "tooling"
    ],
    "langs": [
      {
        "id": "python",
        "label": "Python",
        "code": "import time\nimport os\n\n# ── CONFIG ─────────────────────\nWATCH_DIR = \"./watched\"     # TODO: folder to watch\nPOLL_SECONDS = 2\n\ndef on_change(filename, event):\n    # TODO: replace with your real action\n    print(f\"[{event}] {filename}\")\n\ndef watch():\n    os.makedirs(WATCH_DIR, exist_ok=True)\n    seen = {f: os.path.getmtime(os.path.join(WATCH_DIR, f))\n            for f in os.listdir(WATCH_DIR)}\n\n    while True:\n        time.sleep(POLL_SECONDS)\n        current = os.listdir(WATCH_DIR)\n\n        for f in current:\n            path = os.path.join(WATCH_DIR, f)\n            mtime = os.path.getmtime(path)\n            if f not in seen:\n                on_change(f, \"created\")\n            elif mtime != seen[f]:\n                on_change(f, \"modified\")\n            seen[f] = mtime\n\n        for f in list(seen):\n            if f not in current:\n                on_change(f, \"deleted\")\n                del seen[f]\n\nif __name__ == \"__main__\":\n    watch()"
      },
      {
        "id": "js",
        "label": "Node",
        "code": "const fs = require('fs');\nconst path = require('path');\n\n// ── CONFIG ─────────────────────\nconst WATCH_DIR = './watched';   // TODO: folder to watch\n\nfs.mkdirSync(WATCH_DIR, { recursive: true });\n\nfunction onChange(filename, eventType) {\n  // TODO: replace with your real action\n  console.log(`[${eventType}] ${filename}`);\n}\n\nfs.watch(WATCH_DIR, (eventType, filename) => {\n  if (filename) onChange(filename, eventType);\n});\n\nconsole.log(`Watching ${path.resolve(WATCH_DIR)}...`);"
      }
    ]
  },
  {
    "slug": "cli-tool",
    "title": "CLI Tool Starter",
    "summary": "Argument parsing, verbose flag, and file output already wired up.",
    "category": "tooling",
    "tags": [
      "CLI",
      "tooling"
    ],
    "langs": [
      {
        "id": "python",
        "label": "Python",
        "code": "import argparse\n\ndef main():\n    parser = argparse.ArgumentParser(description=\"TODO: describe your tool\")\n    parser.add_argument(\"input\", help=\"Input file or value\")\n    parser.add_argument(\"-o\", \"--output\", default=None, help=\"Output path\")\n    parser.add_argument(\"-v\", \"--verbose\", action=\"store_true\")\n    args = parser.parse_args()\n\n    if args.verbose:\n        print(f\"Processing: {args.input}\")\n\n    result = process(args.input)   # TODO: your real logic\n\n    if args.output:\n        with open(args.output, \"w\") as f:\n            f.write(result)\n    else:\n        print(result)\n\ndef process(value):\n    return value.upper()   # TODO: replace\n\nif __name__ == \"__main__\":\n    main()"
      },
      {
        "id": "js",
        "label": "Node",
        "code": "#!/usr/bin/env node\nconst args = process.argv.slice(2);\n\n// ── PARSE ─────────────────────\nconst input = args[0];\nconst verbose = args.includes('-v') || args.includes('--verbose');\nconst outIndex = args.findIndex(a => a === '-o' || a === '--output');\nconst output = outIndex !== -1 ? args[outIndex + 1] : null;\n\nif (!input) {\n  console.error('Usage: mytool <input> [-o output] [-v]');\n  process.exit(1);\n}\n\nif (verbose) console.error(`Processing: ${input}`);\n\nconst result = transform(input);   // TODO: your real logic\n\nif (output) {\n  require('fs').writeFileSync(output, result);\n} else {\n  console.log(result);\n}\n\nfunction transform(value) {\n  return value.toUpperCase();   // TODO: replace\n}"
      }
    ]
  },
  {
    "slug": "scheduled-task-runner",
    "title": "Scheduled Task Runner",
    "summary": "Runs jobs on a recurring schedule without cron or a task scheduler service.",
    "category": "tooling",
    "tags": [
      "automation",
      "tooling"
    ],
    "langs": [
      {
        "id": "python",
        "label": "Python",
        "code": "import time\nimport schedule   # pip install schedule\n\n# ── JOBS ─────────────────────\ndef job():\n    # TODO: replace with your real task\n    print(\"Running scheduled job...\")\n\n# ── SCHEDULE ───────────────\nschedule.every(1).hours.do(job)          # TODO: adjust interval\nschedule.every().day.at(\"09:00\").do(job) # TODO: or use a fixed time\n\nif __name__ == \"__main__\":\n    print(\"Scheduler started, waiting for jobs...\")\n    while True:\n        schedule.run_pending()\n        time.sleep(1)"
      },
      {
        "id": "js",
        "label": "Node",
        "code": "const cron = require('node-cron');   // npm install node-cron\n\n// ── JOBS ─────────────────────\nfunction job() {\n  // TODO: replace with your real task\n  console.log('Running scheduled job...');\n}\n\n// ── SCHEDULE ───────────────\ncron.schedule('0 * * * *', job);     // TODO: adjust — this runs hourly\ncron.schedule('0 9 * * *', job);     // TODO: or a fixed daily time\n\nconsole.log('Scheduler started, waiting for jobs...');"
      }
    ]
  }
];
